#!/bin/sh
# File: sfeedrc
# Maintainer: Chris Fröschl <cfroeschl@protonmail.com>
# Last Modified: Wed 30 Dec 2020 11:03:53 AM CET
# License:
# Copyright (c) 2020 Chris Fröschl.
#
# Description:
# Main sfeed config file containing overrides and RSS URLs.

# list of feeds to fetch:
feeds() {
	# feed <name> <feedurl> [basesiteurl] [encoding]
	feed 'RMS' 'https://stallman.org/rss/rss.xml'
	feed 'suckless.org' 'https://suckless.org/atom.xml'
        feed 'cat -v: harmful' 'http://harmful.cat-v.org/Blog/index.rss'
        feed 'cat -v: helpful' 'http://helpful.cat-v.org/Blog/index.rss'
        feed 'cat -v: ninetimes' 'http://ninetimes.cat-v.org/index.atom'
	feed 'gentoo' 'https://planet.gentoo.org/universe/atom.xml'
	feed 'GNU' 'https://planet.gnu.org/rss20.xml'
	feed 'TOR' 'https://blog.torproject.org/rss.xml'
	feed 'NotRelated' 'https://notrelated.libsyn.com/rss'
	feed 'Luke Smith Blog' 'https://lukesmith.xyz/rss.xml'
	feed 'Luke Smith Videos' 'https://videos.lukesmith.xyz/feeds/videos.atom?sort=-trending'
	feed 'Hacker News' 'https://news.ycombinator.com/rss'
}

# Fetch a feed via TOR proxy if source allows it.
# fetch(name, url, feedfile)
fetch() {
    if [ "$2" = "https://boards.4channel.org/g/index.rss" ]; then
        curl --max-redirs 0 -L -m 15 -H "User-Agent:" -f -s "$2" 2>/dev/null
    else
        curl --max-redirs 0 -L -m 15 -H "User-Agent:" -f -s --socks5-hostname localhost:9050 "$2" 2>/dev/null
    fi
}
